### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by buzai** [joenot443/crAIg#1]
.\runtime/marioCraig.lua:66 try call field 'open'(a nil value)

**Comment by taurheim** [comment]
Are you running it using FCEUX?

**Comment by buzai** [comment]
yes,it is win7 and FCEUX2.2

**Comment by buzai** [comment]
# begin the log is : 

# neurons:  175

# neurons:  175

-------------GENERATION----------------
Starting gen  1
Calculating deep fitness for  1  species
Calculating fitness for species  1

#         Genome:  1

then error

**Comment by taurheim** [comment]
I'm having trouble reproducing the error on Windows 10. I'll run a VM later today and see if I can replicate on 7.

**Comment by buzai** [comment]
I have repaired this program, I have a new version of the FCEUX, the previous error disappeared, but with a new problem, the problem is relatively simple, just crate a new folder under the runtime folder is ok, because the save path is  "/runtime / crAIg/crAIg-saved-",but under the runtime can't find crAIgs folder.

**Comment by taurheim** [comment]
There was an issue with the gitignore hiding a folder used during runtime. If you pull the my latest commit it should all work now.

**Comment by buzai** [comment]
OK, But when the program is running the memory will be increased,  Is it  memory leak? After running  sometime,it will not enought memory .

**Comment by taurheim** [comment]
Unfortunately, that's a bug with FCEUX. They limit the amount of memory that a script can use. Using the scripting feature for something as complex as a neural network isn't the intended use for the LUA scripting of FCEUX. We're currently developing our own [NES emulator](https://github.com/taurheim/knaves-nes), for which we're hoping to be able to remove this restriction, but it's a ways off completion.

This means that crAIg can usually only run to generation 8-12 before running out of memory :/. All of the code in /NEAT is emulator-agnostic, though, so if there is another emulator that would allow more memory for scripts then we would be able to use that instead.

**Comment by buzai** [comment]
thank you very much for your help, your code I have seen almost, and gave me a lot of inspiration.
