### ISSUE TITLE
JSON error?

### ISSUE THREAD

**Issue by tevino** [joenot443/crAIg#2]
Hi, I'm trying to run as README says:
1. Clone this repo
2. Download FCEUX
3. Open FCEUX and click File -> Open ROM -> runtime/Super Mario Bros. (Japan, USA).nes
4. Press enter to start the game (wait for mario to be standing on the ground)
5. File -> Lua -> New Lua Script Window
6. Browse... "crAIg.lua"
7. Click "Run"
8. Watch crAIg learn!

But nothing happened after I loaded the script.

Here is the error message:

```
Emulation speed 100.0%
# neurons:  -2.82340373799e+1289

# neurons:  1.06842243992e-4913

-------------GENERATION----------------

Starting gen  2.97695309906e-4911

Calculating deep fitness for  2.97695309906e-4911  species

Calculating fitness for species  2.97695309906e-4911

        Genome:  2.97695309906e-4911

Emulation speed 100.0%
DL sound with pulse driver...
Lua thread bombed out: ./runtime/json.lua:398: conflict converting table with mixed-type keys into a JSON object: key -3 exists both as a string and a number.
Emulation speed 100.0%
```

I'm using FCEUX 2.2.2 on Debian 8.

Before the above error message, I've solved some other like `can not find runtime/json` and `can not find ./NEAT/models/connection` by renaming the related filenames to lower cases.

Am I missing something?

**Comment by joenot443** [comment]
Wasn't able to recreate this, your # of neurons and starting gen numbers suggest an issue with the SDL port of FCEUX (the version used for Unix machines). Would you be able to try it on a Windows machine? Other people have reported issues with certain Lua scripts using the SDL version of FCEUX.

**Comment by tevino** [comment]
Finally got a windows machine, works like a charm.I really hope it for unix though.

Thanks :smile:

**Comment by joenot443** [comment]
Glad to hear it!
