### ISSUE TITLE
newGeneration attempt to index local 'crAIg' (a nil value)

### ISSUE THREAD

**Issue by diflartle** [joenot443/crAIg#3]
Hey, was trying this out and I get the error

> .\NEAT/newGeneration.lua:10: attempt to index local 'crAIg' (a nil value)

Tried fceux 2.2.2 and 2.2.3, but i'm probably missing something obvious. Any suggestions?

Thanks.

**Comment by taurheim** [comment]
Try it now, looks like in crAIg.lua we left in the line that attempts to load a previous generation of crAIg on startup - that could be what is causing the issue.

https://github.com/joenot443/crAIg/blob/master/crAIg.lua#L39

**Comment by diflartle** [comment]
Works great, thanks for that.
